name: test suite
on: [push, pull_request]

jobs:
  check-and-test:
    name: Check and test with ${{matrix.toolchain}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        toolchain: [stable, 1.84.0]
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.toolchain}}
          components: clippy
      - uses: arduino/setup-protoc@v3
      - run: cargo clippy --tests -- -Dwarnings
      - run: cargo build --examples
      - run: cargo test

  documentation:
    name: Document package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: RUSTDOCFLAGS="-D warnings" cargo doc
